### ISSUE TITLE
What are the functions of FB, FBC, F2B and FBFy in your code?

### ISSUE THREAD

**Issue by syf0518** [yuanzhi-zhu/DiffPIR#10]
Thanks for your contribution, it is wonderful.I see FB, FBC, F2B and FBFy are used for FFT in your codes, but I don't know the exact functions of them.I would appreciate it if you could tell me.

**Comment by yuanzhi-zhu** [comment]
Hi,

these variables are indeed some _**intermediate variables**_ produced by this function https://github.com/yuanzhi-zhu/DiffPIR/blob/36e81bc5e80408766830f45674d8f52af79e421b/utils/utils_sisr.py#L78
and then used to calculate the data-solution as in eq(14) in [DPIR](https://arxiv.org/pdf/2008.13751.pdf)
https://github.com/yuanzhi-zhu/DiffPIR/blob/36e81bc5e80408766830f45674d8f52af79e421b/utils/utils_sisr.py#L65
