### ISSUE TITLE
How about unknown complex degradation type?

### ISSUE THREAD

**Issue by green-gooes** [yuanzhi-zhu/DiffPIR#12]
Hi, thanks for the great work first :)

There are 3 types of degradations mentioned in the paper, which have explicit expressions as suggested by Eq. 25, 27, 29.  In real world, the degradation might be complex and unclear, I wonder how to deal with such degradation? could you please give some insights? thanks in advance!

**Comment by yuanzhi-zhu** [comment]
Hi @green-gooes ,

Thank you for your interest, the existing several training-free diffusion-based IR methods such as DDRM, DPS, DDNM and ours all require known degradation operators.

For real-world IR tasks with only paired data, you can either **estimate the degradation kernel** or **train an end-to-end model with synthetic (augmented) data**.

**Comment by green-gooes** [comment]
Thanks for the reply! I will try the second solution.
