### ISSUE TITLE
please give me some guidence for training a Super-Resolution model on my own dataset

### ISSUE THREAD

**Issue by lmvgjp** [yuanzhi-zhu/DiffPIR#14]
Hello,

I am a bit lost of how to start...still reading your great paper, so i still have many things to learn.
The idea is to train the denoiser on my own data to get super-resolution but i am a bit confused with the code.
How do i train a model for that?
thanks a lot!
greetings

**Comment by yuanzhi-zhu** [comment]
Hi @lmvgjp 

Thank you for your interest.

The key idea is that diffusion models are trained as **denoisers** and we can use **pre-trained** diffusion models as plug-and-play image prior(denoisers). 
That's to say, our code base does not involve the training of diffusion models as we use the **pre-trained** ones provided by previous work.

See [this slides](https://yuanzhi-zhu.github.io/documents/slides/diffusion_models_for_pnp_IR.pdf) for a better understanding of our work!

If you want to train a diffusion model from scratch, you can refer to https://github.com/openai/guided-diffusion or https://github.com/NVlabs/edm.

**Comment by lmvgjp** [comment]
Hi Yuanzhi,

Thank you so much for taking your time to advise me! you are very kind
greetings
