### ISSUE TITLE
some strange things when running main_ddpir_inpainting.py

### ISSUE THREAD

**Issue by xinyuw258** [yuanzhi-zhu/DiffPIR#18]
I'm sorry to trouble you, I'm a student. I have some questions to ask you for advice. How long does it take to run main_ddpir_inpainting.py?  I wonder why when I follow the instructions to run this program, the terminal shows that there are no processes and also there are no errors during debugging.
![1](https://github.com/yuanzhi-zhu/DiffPIR/assets/143474423/14c909e9-d1f7-44ff-80ca-d12211b5c795)
![2](https://github.com/yuanzhi-zhu/DiffPIR/assets/143474423/80aa0af5-0f80-44d2-87ae-981d2c634f38)
![3](https://github.com/yuanzhi-zhu/DiffPIR/assets/143474423/510ad74a-8d82-4e68-b641-3abe949bcf51)

**Comment by yuanzhi-zhu** [comment]
Have you tried the other two scripts?

**Comment by xinyuw258** [comment]
yes, there are the same situations. Are there any details in launch.json that instructions don't mention but matter?
![00](https://github.com/yuanzhi-zhu/DiffPIR/assets/143474423/36cfaf45-847e-4f6e-a0b4-1c759088bbc3)
![05](https://github.com/yuanzhi-zhu/DiffPIR/assets/143474423/9f801c7d-de97-4b2f-93c8-072715ce21b3)
![02](https://github.com/yuanzhi-zhu/DiffPIR/assets/143474423/4067f3c2-7c57-48fa-a4c0-ade6673e59af)
![04](https://github.com/yuanzhi-zhu/DiffPIR/assets/143474423/e9062e9e-378b-4b7f-8dc3-ef22e14c0762)
