### ISSUE TITLE
Some questions about the implemented equations in the codes

### ISSUE THREAD

**Issue by dawnlh** [yuanzhi-zhu/DiffPIR#23]
Thanks for sharing the great work! 
I can run the code successfully， but I'm confused with some implementations in `main_ddpir_deblur.py` and respectfully request your help. 

---

https://github.com/yuanzhi-zhu/DiffPIR/blob/88b9b81568c6d0fd84d8ad2092ef856be6afa10d/main_ddpir_deblur.py#L91-L96

In this part, the variables `noise_model_t` and `t_start` are overrided. The initial setting seems to determine the start point for the reverse diffusion (instead of directly from the random noise), but why override them. (I tried the original setting and the performance got worse)

---

https://github.com/yuanzhi-zhu/DiffPIR/blob/88b9b81568c6d0fd84d8ad2092ef856be6afa10d/main_ddpir_deblur.py#L342-L347

These lines are corresponding to Eq.14-15 in the paper, i.e. 
![image](https://github.com/yuanzhi-zhu/DiffPIR/assets/19143656/7e7f3781-cd9a-4ca3-9e45-95321aa314de)

1. I didn't figure out which equation `eta_sigma` in  Line.345  corresponses to in the paper. It looks like $\sigma_t$ in Eq.12 (for DDPM case) of the DDIM paper, but not the same.

2. In Line 346-347, the equation seems to be a combination of Eq.14 and Eq.15, i.e., it contains both $\sigma_{\eta_t}$ and $\zeta$. I know  $\eta$  is set to 0 (thus $\sigma_{\eta_t}=0$, this line corresponse to Eq.15 ) in this code, but I'm confused about the equation's original meaning.

**Comment by yuanzhi-zhu** [comment]
Hi @dawnlh , thanks for your interest in our work.
1. For `noise_model_t`, we use it to skip solving the analytic solution at the end of the sampling process. The intuition behind this is that at a high signal-noise ratio region, the diffusion sampling process does nothing but iteratively denoising, and the measurement information $y$ may not be necessary.
2. For `t_start`, we use it to shortcut to a closer initial point for faster sampling. You may find why on page 18 of this [slide](https://yuanzhi-zhu.github.io/documents/slides/diffusion_models_for_pnp_IR.pdf#18).
3. Sorry for the confusion and you are mostly correct that _In Line 346-347, the equation seems to be a combination of Eq.14 and Eq.15_, where `eta_sigma` is the $\sigma_{\eta_t}$ in eq (14) (the DDIM formula). The $\zeta$ in eq(15) is a bit hand-wavy and more like an experimental result.

We intend to leave all the tunable hyperparameters that appear in the paper in this code base for people to try. By tuning them, I believe one can better understand this method.

Hope these can address your concerns and please do not hesitate if you have any other questions

**Comment by dawnlh** [comment]
Got it! Thank you for your prompt response and kind explanation. 😄

**Comment by taoyangworld** [comment]
Hi @dawnlh , thanks for your thoughtful questions! I actually have the same confusion and would really appreciate hearing your perspective. 

In Questions 1 and 2, the authors state that the purposes are to avoid solving the analytic solution at the final step of the sampling process and to shortcut to a point closer to the solution for faster sampling, respectively. These intentions seem to correspond to Line 91 and Line 95. However, it appears that Line 92 and Line 96 immediately overwrite the values, which seems to undermine the intended effect. I'm not sure about the purpose of overwrite

I'd be very grateful if you could share how you understand this part. Thank you again for your time and generosity!

**Comment by dawnlh** [comment]
Hi @taoyangworld , sorry, but it has been so long since I raised this issue, and I'm not sure about the answer now 😄 . Perhaps @yuanzhi-zhu could provide more help.

**Comment by taoyangworld** [comment]
@dawnlh ok, thanks for you response! wish you all the best!
