### ISSUE TITLE
Advice on inference for different resolutions?

### ISSUE THREAD

**Issue by savvaki** [yuanzhi-zhu/DiffPIR#24]
Good day,

Thank you very much for your work. I would like to know if you could provide advice on applying the models for resolutions other than 256x256, for example for larger images. Are we limited because of the pretrained diffusion models?

Thanks in advance!

**Comment by yuanzhi-zhu** [comment]
hi @savvaki,
you are absolutely right, the only constraints come from the pretrained diffusion model.
as long as you find a pretrained model on a larger resolution, you can simply adapt the code for your task

**Comment by savvaki** [comment]
Thanks for the response I appreciate that! One last question for my understanding... aren't these unconditional diffusion models fully convolutional unets? Why can't one model work for different resolutions? Sorry if that's a silly question, thanks again.

**Comment by yuanzhi-zhu** [comment]
that's an excellent question many people ignored!
indeed, most of the diffusion models you can find have attention modules (self-attentions for those unconditional ones).
There are indeed diffusion models (fully convolutional unets) trained just like traditional denoisers on image patchs of resolution like 96 and 128. However, one of the advantages of our method is to leverage the generative prior from those existing powerful diffusion models and unfortunately they are mostly not fully cnn based.
feel free to ask if you have any further questoin
