### ISSUE TITLE
FFHQ 256×256 and ImageNet 256×256 validation dataset

### ISSUE THREAD

**Issue by NebiyouTen** [yuanzhi-zhu/DiffPIR#27]
Dear Authors,

Thanks for your great work and for sharing your code!

I am currently working on reproducing the results, and I wanted to ask how you sampled the 100 images for evaluation (if possible, which specific samples were used) and how they were pre-processed to obtain the final 256x256 HR images for each dataset.

Thank you.

**Comment by yuanzhi-zhu** [comment]
Hi @NebiyouTen,

I have just uploaded the names of the validation data at https://github.com/yuanzhi-zhu/DiffPIR/blob/main/testsets/ffhq_val_100/ffhq_val_100.txt and https://github.com/yuanzhi-zhu/DiffPIR/blob/main/testsets/imagenet_val_100/imagenet_val_100.txt.

You can download them from the corresponding 256*256 datasets.

**Comment by NebiyouTen** [comment]
Thank you.
