### ISSUE TITLE
Results of DPIR baseline

### ISSUE THREAD

**Issue by ChongWang1024** [yuanzhi-zhu/DiffPIR#29]
Hi, 

Thank you so much for sharing such an interesting work.
I have a question about the results of DPIR on FFHQ and ImageNet (since these datasets are not evaluated in the original DPIR paper).
Do you train the DPIR denoiser on FFHQ and ImageNet separately or directly use the original pretrained DPIR?

Thanks in advance!

**Comment by yuanzhi-zhu** [comment]
Hi,
As mentioned in the paper,
> To ensure fairness, we employed the same pre-trained diffusion models and blur kernels for all methods in the comparison.
the same pre-trained diffusion models are used as denoisers to evaluate DPIR.

**Comment by ChongWang1024** [comment]
Hi,
Thanks for your prompt reply.
So you use the same network trained using diffusion training, and directly plugging into the DPIR iteration to produce the result?

**Comment by yuanzhi-zhu** [comment]
Exactly, as we have argued in the paper that diffusion models are trained as denoisers (and we can use them as denoisers!)

**Comment by ChongWang1024** [comment]
Interesting! this has addressed my question.

**Comment by yuanzhi-zhu** [comment]
@ChongWang1024 you may want to have a look at this [slide](https://yuanzhi-zhu.github.io/documents/slides/diffusion_models_for_pnp_IR.pdf) to better (than the paper) understand this work (and related works)

**Comment by ChongWang1024** [comment]
> @ChongWang1024 you may want to have a look at this [slide](https://yuanzhi-zhu.github.io/documents/slides/diffusion_models_for_pnp_IR.pdf) to better (than the paper) understand this work (and related works)

Thanks, these slides help a lot!
