### ISSUE TITLE
Model file error

### ISSUE THREAD

**Issue by Auroa-smart** [yuanzhi-zhu/DiffPIR#37]
Hello, I would like to ask if the file on the link (https://drive.google.com/drive/folders/1jElnRoFv7b31fG0v6pTSQkelbSX3xGZh?usp=sharing) is corrupted, because I download the model file when I run it many times and still can't open ffhq_10m.pt.[
<img width="750" alt="78613c1906da24c09793f6201d0bca0" src="https://github.com/yuanzhi-zhu/DiffPIR/assets/103878335/060058d2-e1b6-48d0-b2b1-b3542858a1ec">
](url)

**Comment by 2000lf** [comment]
> Hello, I would like to ask if the file on the link (https://drive.google.com/drive/folders/1jElnRoFv7b31fG0v6pTSQkelbSX3xGZh?usp=sharing) is corrupted, because I download the model file when I run it many times and still can't open ffhq_10m.pt.[ <img alt="78613c1906da24c09793f6201d0bca0" width="750" src="https://private-user-images.githubusercontent.com/103878335/344362909-060058d2-e1b6-48d0-b2b1-b3542858a1ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwOTU5MzMsIm5iZiI6MTczNzA5NTYzMywicGF0aCI6Ii8xMDM4NzgzMzUvMzQ0MzYyOTA5LTA2MDA1OGQyLWUxYjYtNDhkMC1iMmIxLWIzNTQyODU4YTFlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExN1QwNjMzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQxNDY1NmE2NWM3ODNkZDBjYzZkYTVkZTBkZGY1ZWYyN2RiNGM0NWJmYjViNmVjYjU5MTA0NDEyNDU2OGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yFjvi2yuLB-hY9RYsHjzlG9LNjZA4Ko8Vq9cjk32UzM"> ](url)

did you solve it?
