### ISSUE TITLE
ModuleNotFoundError: No module named 'motionblur'

### ISSUE THREAD

**Issue by syf0518** [yuanzhi-zhu/DiffPIR#4]
I encountered this error and tried to download 'motionblur' but failed. I would like to ask you how to download it, I can't find its installation package on PyPI.

**Comment by yuanzhi-zhu** [comment]
Hi @syf0518,

Could you please try the following 

> for motion blur, please download https://github.com/LeviBorodenko/motionblur to the DiffPIR folder.

as mentioned here https://github.com/yuanzhi-zhu/DiffPIR#clone-and-install.

**Comment by syf0518** [comment]
> Hi @syf0518,
> 
> Could you please try the following
> 
> > for motion blur, please download https://github.com/LeviBorodenko/motionblur to the DiffPIR folder.
> 
> as mentioned here https://github.com/yuanzhi-zhu/DiffPIR#clone-and-install.

Thank you very much.
