### ISSUE TITLE
有关generate_mode的问题

### ISSUE THREAD

**Issue by Case3y** [yuanzhi-zhu/DiffPIR#40]
我想问下作者代码里的generate_mode包含了DPS，DiffPIR，Repaint和vanilla。其中的DPS和Repaint是不是就是原论文方法的复现，还是和原方法有些区别？
感谢作者的工作！

**Comment by yuanzhi-zhu** [comment]
都是我试图复现原论文的代码，仅供参考和学习，并不用于重视复现原论文。
论文中使用的对比方法都是用的原论文的代码运行得到的

**Comment by Case3y** [comment]
感谢谢作者的回复
