### ISSUE TITLE
Comparisons with DDRM - Operators

### ISSUE THREAD

**Issue by SavvasMel** [yuanzhi-zhu/DiffPIR#5]
Hello,

That is a very interesting work, and a very tidy code, well done!

I would like to ask what changes needed to be made in the DDRM code so that DiffPIR's operators and DDRM's operators can match properly. What I find is that if I create a noisy image with the DiffPIR code (let's say by creating a Gaussian blur of size 9x9 and st. deviation 3) and a noisy image with the DDRM code (again the same operator but with their zero-padded strategy code), the DDRM's noisy image is a more challenging one. 

I am trying to compare the two algorithms in the most fair way, so I am not sure if the operators are the same. Could you help me on that please? How did you make the comparisons in the paper towards this?

**Comment by yuanzhi-zhu** [comment]
Hi @SavvasMel ,
Thank you for your interest!

The bluring operator in our work is inherent from [DPS](https://github.com/DPS2022/diffusion-posterior-sampling). 

Unfortunately, we tuned the hyper-parameters of the degradation operator by hand to match the performance of the operators in different methods :( Additionally, I am unaware of the theoretical connection between the two settings of operators.

Let me know if this answers your question.

**Comment by SavvasMel** [comment]
I am sorry for the late response. Yes, this answers my question, thank you very much for your prompt response! Just another quick question: 

I see that your code is adapted also to run DPS but there is one step that produces an error for me and specifically this part 

if generate_mode == 'DPS_y0':
          norm_grad, norm = utils_model.grad_and_value(operator=Tx,x=x, x_hat=x0, measurement=y)
          #norm_grad, norm = utils_model.grad_and_value(operator=Tx,x=xt, x_hat=x0, measurement=y)                                                                                
          x = xt - norm_grad * 1. #norm / (2*rhos[t_i]) 
          x = x.detach_()

This part requires x0 to have a gradient requirement because the norm_grad is calculated w.r.t to x0 and not x (which has a gradient requirement). I am not sure what would be the best to change here. I would much appreciate if you could help towards this.
